### ISSUE TITLE
Won't work in releases

### ISSUE THREAD

**Issue by bitwalker** [princemaple/clusterable#1]
Hi!

I took a glance through the library, and wanted to bring up the issue that this library won't work in releases, as `:net_kernel` will already be started, and the cookie will already be set. Since that's the bulk of what Clusterable does, probably all you need to do is make a note in the README that it's not compatible. Alternatively you can check to see if `:net_kernel` is started and skip those steps.

**Comment by princemaple** [comment]
Thanks! I'll add a note.
